packages:
  - app
  - convex
  - packages/*
  - local/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - nx
  - protobufjs
  - sharp
  - sqlite3
  - unrs-resolver

overrides:
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
