/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as filesLayoutRouteImport } from './routes/(files)/layout'
import { Route as chatLayoutRouteImport } from './routes/(chat)/layout'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRecoverAccountRouteImport } from './routes/auth/recover-account'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as filesFilesRouteImport } from './routes/(files)/files'
import { Route as AuthTwoFactorIndexRouteImport } from './routes/auth/two-factor/index'
import { Route as chatChatIndexRouteImport } from './routes/(chat)/chat/index'
import { Route as AuthTwoFactorOtpRouteImport } from './routes/auth/two-factor/otp'
import { Route as chatChatThreadIdRouteImport } from './routes/(chat)/chat/$threadId'
import { Route as AuthAcceptInvitationInvitationIdIndexRouteImport } from './routes/auth/accept-invitation/$invitationId/index'
import { Route as DashboardSettingsAuthSecurityRouteImport } from './routes/dashboard/settings/auth/security'
import { Route as DashboardSettingsAuthOrganizationsRouteImport } from './routes/dashboard/settings/auth/organizations'
import { Route as DashboardSettingsAuthOrganizationRouteImport } from './routes/dashboard/settings/auth/organization'
import { Route as DashboardSettingsAuthMembersRouteImport } from './routes/dashboard/settings/auth/members'
import { Route as DashboardSettingsAuthApiKeysRouteImport } from './routes/dashboard/settings/auth/api-keys'
import { Route as DashboardSettingsAuthAccountRouteImport } from './routes/dashboard/settings/auth/account'
import { Route as DashboardSettingsAiUsageAnalyticsRouteImport } from './routes/dashboard/settings/ai/usage-analytics'
import { Route as DashboardSettingsAiProvidersRouteImport } from './routes/dashboard/settings/ai/providers'
import { Route as DashboardSettingsAiPersonalizationRouteImport } from './routes/dashboard/settings/ai/personalization'
import { Route as DashboardSettingsAiOptionsRouteImport } from './routes/dashboard/settings/ai/options'
import { Route as DashboardSettingsAiModelsRouteImport } from './routes/dashboard/settings/ai/models'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'
import { ServerRoute as ApiAiMcpTransportServerRouteImport } from './routes/api/ai/mcp/$transport'

const rootServerRouteImport = createServerRootRoute()

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const filesLayoutRoute = filesLayoutRouteImport.update({
  id: '/(files)',
  getParentRoute: () => rootRouteImport,
} as any)
const chatLayoutRoute = chatLayoutRouteImport.update({
  id: '/(chat)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthRecoverAccountRoute = AuthRecoverAccountRouteImport.update({
  id: '/recover-account',
  path: '/recover-account',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const filesFilesRoute = filesFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => filesLayoutRoute,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const chatChatIndexRoute = chatChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => chatLayoutRoute,
} as any)
const AuthTwoFactorOtpRoute = AuthTwoFactorOtpRouteImport.update({
  id: '/two-factor/otp',
  path: '/two-factor/otp',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const chatChatThreadIdRoute = chatChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => chatLayoutRoute,
} as any)
const AuthAcceptInvitationInvitationIdIndexRoute =
  AuthAcceptInvitationInvitationIdIndexRouteImport.update({
    id: '/accept-invitation/$invitationId/',
    path: '/accept-invitation/$invitationId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const DashboardSettingsAuthSecurityRoute =
  DashboardSettingsAuthSecurityRouteImport.update({
    id: '/settings/auth/security',
    path: '/settings/auth/security',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAuthOrganizationsRoute =
  DashboardSettingsAuthOrganizationsRouteImport.update({
    id: '/settings/auth/organizations',
    path: '/settings/auth/organizations',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAuthOrganizationRoute =
  DashboardSettingsAuthOrganizationRouteImport.update({
    id: '/settings/auth/organization',
    path: '/settings/auth/organization',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAuthMembersRoute =
  DashboardSettingsAuthMembersRouteImport.update({
    id: '/settings/auth/members',
    path: '/settings/auth/members',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAuthApiKeysRoute =
  DashboardSettingsAuthApiKeysRouteImport.update({
    id: '/settings/auth/api-keys',
    path: '/settings/auth/api-keys',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAuthAccountRoute =
  DashboardSettingsAuthAccountRouteImport.update({
    id: '/settings/auth/account',
    path: '/settings/auth/account',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAiUsageAnalyticsRoute =
  DashboardSettingsAiUsageAnalyticsRouteImport.update({
    id: '/settings/ai/usage-analytics',
    path: '/settings/ai/usage-analytics',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAiProvidersRoute =
  DashboardSettingsAiProvidersRouteImport.update({
    id: '/settings/ai/providers',
    path: '/settings/ai/providers',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAiPersonalizationRoute =
  DashboardSettingsAiPersonalizationRouteImport.update({
    id: '/settings/ai/personalization',
    path: '/settings/ai/personalization',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAiOptionsRoute =
  DashboardSettingsAiOptionsRouteImport.update({
    id: '/settings/ai/options',
    path: '/settings/ai/options',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardSettingsAiModelsRoute =
  DashboardSettingsAiModelsRouteImport.update({
    id: '/settings/ai/models',
    path: '/settings/ai/models',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAiMcpTransportServerRoute = ApiAiMcpTransportServerRouteImport.update({
  id: '/api/ai/mcp/$transport',
  path: '/api/ai/mcp/$transport',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/files': typeof filesFilesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/chat/$threadId': typeof chatChatThreadIdRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/chat': typeof chatChatIndexRoute
  '/auth/two-factor': typeof AuthTwoFactorIndexRoute
  '/dashboard/settings/ai/models': typeof DashboardSettingsAiModelsRoute
  '/dashboard/settings/ai/options': typeof DashboardSettingsAiOptionsRoute
  '/dashboard/settings/ai/personalization': typeof DashboardSettingsAiPersonalizationRoute
  '/dashboard/settings/ai/providers': typeof DashboardSettingsAiProvidersRoute
  '/dashboard/settings/ai/usage-analytics': typeof DashboardSettingsAiUsageAnalyticsRoute
  '/dashboard/settings/auth/account': typeof DashboardSettingsAuthAccountRoute
  '/dashboard/settings/auth/api-keys': typeof DashboardSettingsAuthApiKeysRoute
  '/dashboard/settings/auth/members': typeof DashboardSettingsAuthMembersRoute
  '/dashboard/settings/auth/organization': typeof DashboardSettingsAuthOrganizationRoute
  '/dashboard/settings/auth/organizations': typeof DashboardSettingsAuthOrganizationsRoute
  '/dashboard/settings/auth/security': typeof DashboardSettingsAuthSecurityRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/files': typeof filesFilesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/chat/$threadId': typeof chatChatThreadIdRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/chat': typeof chatChatIndexRoute
  '/auth/two-factor': typeof AuthTwoFactorIndexRoute
  '/dashboard/settings/ai/models': typeof DashboardSettingsAiModelsRoute
  '/dashboard/settings/ai/options': typeof DashboardSettingsAiOptionsRoute
  '/dashboard/settings/ai/personalization': typeof DashboardSettingsAiPersonalizationRoute
  '/dashboard/settings/ai/providers': typeof DashboardSettingsAiProvidersRoute
  '/dashboard/settings/ai/usage-analytics': typeof DashboardSettingsAiUsageAnalyticsRoute
  '/dashboard/settings/auth/account': typeof DashboardSettingsAuthAccountRoute
  '/dashboard/settings/auth/api-keys': typeof DashboardSettingsAuthApiKeysRoute
  '/dashboard/settings/auth/members': typeof DashboardSettingsAuthMembersRoute
  '/dashboard/settings/auth/organization': typeof DashboardSettingsAuthOrganizationRoute
  '/dashboard/settings/auth/organizations': typeof DashboardSettingsAuthOrganizationsRoute
  '/dashboard/settings/auth/security': typeof DashboardSettingsAuthSecurityRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(chat)': typeof chatLayoutRouteWithChildren
  '/(files)': typeof filesLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/(files)/files': typeof filesFilesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover-account': typeof AuthRecoverAccountRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/(public)/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(chat)/chat/$threadId': typeof chatChatThreadIdRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/(chat)/chat/': typeof chatChatIndexRoute
  '/auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/dashboard/settings/ai/models': typeof DashboardSettingsAiModelsRoute
  '/dashboard/settings/ai/options': typeof DashboardSettingsAiOptionsRoute
  '/dashboard/settings/ai/personalization': typeof DashboardSettingsAiPersonalizationRoute
  '/dashboard/settings/ai/providers': typeof DashboardSettingsAiProvidersRoute
  '/dashboard/settings/ai/usage-analytics': typeof DashboardSettingsAiUsageAnalyticsRoute
  '/dashboard/settings/auth/account': typeof DashboardSettingsAuthAccountRoute
  '/dashboard/settings/auth/api-keys': typeof DashboardSettingsAuthApiKeysRoute
  '/dashboard/settings/auth/members': typeof DashboardSettingsAuthMembersRoute
  '/dashboard/settings/auth/organization': typeof DashboardSettingsAuthOrganizationRoute
  '/dashboard/settings/auth/organizations': typeof DashboardSettingsAuthOrganizationsRoute
  '/dashboard/settings/auth/security': typeof DashboardSettingsAuthSecurityRoute
  '/auth/accept-invitation/$invitationId/': typeof AuthAcceptInvitationInvitationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/files'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/'
    | '/chat/$threadId'
    | '/auth/two-factor/otp'
    | '/chat'
    | '/auth/two-factor'
    | '/dashboard/settings/ai/models'
    | '/dashboard/settings/ai/options'
    | '/dashboard/settings/ai/personalization'
    | '/dashboard/settings/ai/providers'
    | '/dashboard/settings/ai/usage-analytics'
    | '/dashboard/settings/auth/account'
    | '/dashboard/settings/auth/api-keys'
    | '/dashboard/settings/auth/members'
    | '/dashboard/settings/auth/organization'
    | '/dashboard/settings/auth/organizations'
    | '/dashboard/settings/auth/security'
    | '/auth/accept-invitation/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/files'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard'
    | '/chat/$threadId'
    | '/auth/two-factor/otp'
    | '/chat'
    | '/auth/two-factor'
    | '/dashboard/settings/ai/models'
    | '/dashboard/settings/ai/options'
    | '/dashboard/settings/ai/personalization'
    | '/dashboard/settings/ai/providers'
    | '/dashboard/settings/ai/usage-analytics'
    | '/dashboard/settings/auth/account'
    | '/dashboard/settings/auth/api-keys'
    | '/dashboard/settings/auth/members'
    | '/dashboard/settings/auth/organization'
    | '/dashboard/settings/auth/organizations'
    | '/dashboard/settings/auth/security'
    | '/auth/accept-invitation/$invitationId'
  id:
    | '__root__'
    | '/(chat)'
    | '/(files)'
    | '/auth'
    | '/dashboard'
    | '/(files)/files'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/recover-account'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/(public)/'
    | '/dashboard/'
    | '/(chat)/chat/$threadId'
    | '/auth/two-factor/otp'
    | '/(chat)/chat/'
    | '/auth/two-factor/'
    | '/dashboard/settings/ai/models'
    | '/dashboard/settings/ai/options'
    | '/dashboard/settings/ai/personalization'
    | '/dashboard/settings/ai/providers'
    | '/dashboard/settings/ai/usage-analytics'
    | '/dashboard/settings/auth/account'
    | '/dashboard/settings/auth/api-keys'
    | '/dashboard/settings/auth/members'
    | '/dashboard/settings/auth/organization'
    | '/dashboard/settings/auth/organizations'
    | '/dashboard/settings/auth/security'
    | '/auth/accept-invitation/$invitationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  chatLayoutRoute: typeof chatLayoutRouteWithChildren
  filesLayoutRoute: typeof filesLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/ai/mcp/$transport'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/ai/mcp/$transport'
  id: '__root__' | '/api/auth/$' | '/api/ai/mcp/$transport'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiAiMcpTransportServerRoute: typeof ApiAiMcpTransportServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(files)': {
      id: '/(files)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof filesLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(chat)': {
      id: '/(chat)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof chatLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/recover-account': {
      id: '/auth/recover-account'
      path: '/recover-account'
      fullPath: '/auth/recover-account'
      preLoaderRoute: typeof AuthRecoverAccountRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/(files)/files': {
      id: '/(files)/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof filesFilesRouteImport
      parentRoute: typeof filesLayoutRoute
    }
    '/auth/two-factor/': {
      id: '/auth/two-factor/'
      path: '/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/(chat)/chat/': {
      id: '/(chat)/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof chatChatIndexRouteImport
      parentRoute: typeof chatLayoutRoute
    }
    '/auth/two-factor/otp': {
      id: '/auth/two-factor/otp'
      path: '/two-factor/otp'
      fullPath: '/auth/two-factor/otp'
      preLoaderRoute: typeof AuthTwoFactorOtpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/(chat)/chat/$threadId': {
      id: '/(chat)/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof chatChatThreadIdRouteImport
      parentRoute: typeof chatLayoutRoute
    }
    '/auth/accept-invitation/$invitationId/': {
      id: '/auth/accept-invitation/$invitationId/'
      path: '/accept-invitation/$invitationId'
      fullPath: '/auth/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/settings/auth/security': {
      id: '/dashboard/settings/auth/security'
      path: '/settings/auth/security'
      fullPath: '/dashboard/settings/auth/security'
      preLoaderRoute: typeof DashboardSettingsAuthSecurityRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/auth/organizations': {
      id: '/dashboard/settings/auth/organizations'
      path: '/settings/auth/organizations'
      fullPath: '/dashboard/settings/auth/organizations'
      preLoaderRoute: typeof DashboardSettingsAuthOrganizationsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/auth/organization': {
      id: '/dashboard/settings/auth/organization'
      path: '/settings/auth/organization'
      fullPath: '/dashboard/settings/auth/organization'
      preLoaderRoute: typeof DashboardSettingsAuthOrganizationRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/auth/members': {
      id: '/dashboard/settings/auth/members'
      path: '/settings/auth/members'
      fullPath: '/dashboard/settings/auth/members'
      preLoaderRoute: typeof DashboardSettingsAuthMembersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/auth/api-keys': {
      id: '/dashboard/settings/auth/api-keys'
      path: '/settings/auth/api-keys'
      fullPath: '/dashboard/settings/auth/api-keys'
      preLoaderRoute: typeof DashboardSettingsAuthApiKeysRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/auth/account': {
      id: '/dashboard/settings/auth/account'
      path: '/settings/auth/account'
      fullPath: '/dashboard/settings/auth/account'
      preLoaderRoute: typeof DashboardSettingsAuthAccountRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/ai/usage-analytics': {
      id: '/dashboard/settings/ai/usage-analytics'
      path: '/settings/ai/usage-analytics'
      fullPath: '/dashboard/settings/ai/usage-analytics'
      preLoaderRoute: typeof DashboardSettingsAiUsageAnalyticsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/ai/providers': {
      id: '/dashboard/settings/ai/providers'
      path: '/settings/ai/providers'
      fullPath: '/dashboard/settings/ai/providers'
      preLoaderRoute: typeof DashboardSettingsAiProvidersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/ai/personalization': {
      id: '/dashboard/settings/ai/personalization'
      path: '/settings/ai/personalization'
      fullPath: '/dashboard/settings/ai/personalization'
      preLoaderRoute: typeof DashboardSettingsAiPersonalizationRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/ai/options': {
      id: '/dashboard/settings/ai/options'
      path: '/settings/ai/options'
      fullPath: '/dashboard/settings/ai/options'
      preLoaderRoute: typeof DashboardSettingsAiOptionsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/ai/models': {
      id: '/dashboard/settings/ai/models'
      path: '/settings/ai/models'
      fullPath: '/dashboard/settings/ai/models'
      preLoaderRoute: typeof DashboardSettingsAiModelsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/ai/mcp/$transport': {
      id: '/api/ai/mcp/$transport'
      path: '/api/ai/mcp/$transport'
      fullPath: '/api/ai/mcp/$transport'
      preLoaderRoute: typeof ApiAiMcpTransportServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface chatLayoutRouteChildren {
  chatChatThreadIdRoute: typeof chatChatThreadIdRoute
  chatChatIndexRoute: typeof chatChatIndexRoute
}

const chatLayoutRouteChildren: chatLayoutRouteChildren = {
  chatChatThreadIdRoute: chatChatThreadIdRoute,
  chatChatIndexRoute: chatChatIndexRoute,
}

const chatLayoutRouteWithChildren = chatLayoutRoute._addFileChildren(
  chatLayoutRouteChildren,
)

interface filesLayoutRouteChildren {
  filesFilesRoute: typeof filesFilesRoute
}

const filesLayoutRouteChildren: filesLayoutRouteChildren = {
  filesFilesRoute: filesFilesRoute,
}

const filesLayoutRouteWithChildren = filesLayoutRoute._addFileChildren(
  filesLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthRecoverAccountRoute: typeof AuthRecoverAccountRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorOtpRoute: typeof AuthTwoFactorOtpRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
  AuthAcceptInvitationInvitationIdIndexRoute: typeof AuthAcceptInvitationInvitationIdIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthRecoverAccountRoute: AuthRecoverAccountRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorOtpRoute: AuthTwoFactorOtpRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
  AuthAcceptInvitationInvitationIdIndexRoute:
    AuthAcceptInvitationInvitationIdIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsAiModelsRoute: typeof DashboardSettingsAiModelsRoute
  DashboardSettingsAiOptionsRoute: typeof DashboardSettingsAiOptionsRoute
  DashboardSettingsAiPersonalizationRoute: typeof DashboardSettingsAiPersonalizationRoute
  DashboardSettingsAiProvidersRoute: typeof DashboardSettingsAiProvidersRoute
  DashboardSettingsAiUsageAnalyticsRoute: typeof DashboardSettingsAiUsageAnalyticsRoute
  DashboardSettingsAuthAccountRoute: typeof DashboardSettingsAuthAccountRoute
  DashboardSettingsAuthApiKeysRoute: typeof DashboardSettingsAuthApiKeysRoute
  DashboardSettingsAuthMembersRoute: typeof DashboardSettingsAuthMembersRoute
  DashboardSettingsAuthOrganizationRoute: typeof DashboardSettingsAuthOrganizationRoute
  DashboardSettingsAuthOrganizationsRoute: typeof DashboardSettingsAuthOrganizationsRoute
  DashboardSettingsAuthSecurityRoute: typeof DashboardSettingsAuthSecurityRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsAiModelsRoute: DashboardSettingsAiModelsRoute,
  DashboardSettingsAiOptionsRoute: DashboardSettingsAiOptionsRoute,
  DashboardSettingsAiPersonalizationRoute:
    DashboardSettingsAiPersonalizationRoute,
  DashboardSettingsAiProvidersRoute: DashboardSettingsAiProvidersRoute,
  DashboardSettingsAiUsageAnalyticsRoute:
    DashboardSettingsAiUsageAnalyticsRoute,
  DashboardSettingsAuthAccountRoute: DashboardSettingsAuthAccountRoute,
  DashboardSettingsAuthApiKeysRoute: DashboardSettingsAuthApiKeysRoute,
  DashboardSettingsAuthMembersRoute: DashboardSettingsAuthMembersRoute,
  DashboardSettingsAuthOrganizationRoute:
    DashboardSettingsAuthOrganizationRoute,
  DashboardSettingsAuthOrganizationsRoute:
    DashboardSettingsAuthOrganizationsRoute,
  DashboardSettingsAuthSecurityRoute: DashboardSettingsAuthSecurityRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  chatLayoutRoute: chatLayoutRouteWithChildren,
  filesLayoutRoute: filesLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiAiMcpTransportServerRoute: ApiAiMcpTransportServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
