/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as chatLayoutRouteImport } from './routes/(chat)/layout'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as AuthTwoFactorIndexRouteImport } from './routes/auth/two-factor/index'
import { Route as chatChatIndexRouteImport } from './routes/(chat)/chat/index'
import { Route as AuthTwoFactorOtpRouteImport } from './routes/auth/two-factor/otp'
import { Route as chatChatThreadIdRouteImport } from './routes/(chat)/chat/$threadId'
import { Route as AuthAcceptInvitationInvitationIdIndexRouteImport } from './routes/auth/accept-invitation/$invitationId/index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'
import { ServerRoute as ApiAiMcpTransportServerRouteImport } from './routes/api/ai/mcp/$transport'

const rootServerRouteImport = createServerRootRoute()

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const chatLayoutRoute = chatLayoutRouteImport.update({
  id: '/(chat)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthTwoFactorIndexRoute = AuthTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const chatChatIndexRoute = chatChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => chatLayoutRoute,
} as any)
const AuthTwoFactorOtpRoute = AuthTwoFactorOtpRouteImport.update({
  id: '/two-factor/otp',
  path: '/two-factor/otp',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const chatChatThreadIdRoute = chatChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => chatLayoutRoute,
} as any)
const AuthAcceptInvitationInvitationIdIndexRoute =
  AuthAcceptInvitationInvitationIdIndexRouteImport.update({
    id: '/accept-invitation/$invitationId/',
    path: '/accept-invitation/$invitationId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAiMcpTransportServerRoute = ApiAiMcpTransportServerRouteImport.update({
  id: '/api/ai/mcp/$transport',
  path: '/api/ai/mcp/$transport',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/chat/$threadId': typeof chatChatThreadIdRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/chat': typeof chatChatIndexRoute
  '/auth/two-factor': typeof AuthTwoFactorIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/chat/$threadId': typeof chatChatThreadIdRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/chat': typeof chatChatIndexRoute
  '/auth/two-factor': typeof AuthTwoFactorIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(chat)': typeof chatLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/(public)/': typeof publicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(chat)/chat/$threadId': typeof chatChatThreadIdRoute
  '/auth/two-factor/otp': typeof AuthTwoFactorOtpRoute
  '/(chat)/chat/': typeof chatChatIndexRoute
  '/auth/two-factor/': typeof AuthTwoFactorIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/auth/accept-invitation/$invitationId/': typeof AuthAcceptInvitationInvitationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/'
    | '/chat/$threadId'
    | '/auth/two-factor/otp'
    | '/chat'
    | '/auth/two-factor'
    | '/dashboard/settings'
    | '/auth/accept-invitation/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard'
    | '/chat/$threadId'
    | '/auth/two-factor/otp'
    | '/chat'
    | '/auth/two-factor'
    | '/dashboard/settings'
    | '/auth/accept-invitation/$invitationId'
  id:
    | '__root__'
    | '/(chat)'
    | '/auth'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/(public)/'
    | '/dashboard/'
    | '/(chat)/chat/$threadId'
    | '/auth/two-factor/otp'
    | '/(chat)/chat/'
    | '/auth/two-factor/'
    | '/dashboard/settings/'
    | '/auth/accept-invitation/$invitationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  chatLayoutRoute: typeof chatLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/ai/mcp/$transport': typeof ApiAiMcpTransportServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/ai/mcp/$transport'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/ai/mcp/$transport'
  id: '__root__' | '/api/auth/$' | '/api/ai/mcp/$transport'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiAiMcpTransportServerRoute: typeof ApiAiMcpTransportServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(chat)': {
      id: '/(chat)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof chatLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/two-factor/': {
      id: '/auth/two-factor/'
      path: '/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/(chat)/chat/': {
      id: '/(chat)/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof chatChatIndexRouteImport
      parentRoute: typeof chatLayoutRoute
    }
    '/auth/two-factor/otp': {
      id: '/auth/two-factor/otp'
      path: '/two-factor/otp'
      fullPath: '/auth/two-factor/otp'
      preLoaderRoute: typeof AuthTwoFactorOtpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/(chat)/chat/$threadId': {
      id: '/(chat)/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof chatChatThreadIdRouteImport
      parentRoute: typeof chatLayoutRoute
    }
    '/auth/accept-invitation/$invitationId/': {
      id: '/auth/accept-invitation/$invitationId/'
      path: '/accept-invitation/$invitationId'
      fullPath: '/auth/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/ai/mcp/$transport': {
      id: '/api/ai/mcp/$transport'
      path: '/api/ai/mcp/$transport'
      fullPath: '/api/ai/mcp/$transport'
      preLoaderRoute: typeof ApiAiMcpTransportServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface chatLayoutRouteChildren {
  chatChatThreadIdRoute: typeof chatChatThreadIdRoute
  chatChatIndexRoute: typeof chatChatIndexRoute
}

const chatLayoutRouteChildren: chatLayoutRouteChildren = {
  chatChatThreadIdRoute: chatChatThreadIdRoute,
  chatChatIndexRoute: chatChatIndexRoute,
}

const chatLayoutRouteWithChildren = chatLayoutRoute._addFileChildren(
  chatLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorOtpRoute: typeof AuthTwoFactorOtpRoute
  AuthTwoFactorIndexRoute: typeof AuthTwoFactorIndexRoute
  AuthAcceptInvitationInvitationIdIndexRoute: typeof AuthAcceptInvitationInvitationIdIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorOtpRoute: AuthTwoFactorOtpRoute,
  AuthTwoFactorIndexRoute: AuthTwoFactorIndexRoute,
  AuthAcceptInvitationInvitationIdIndexRoute:
    AuthAcceptInvitationInvitationIdIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  chatLayoutRoute: chatLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiAiMcpTransportServerRoute: ApiAiMcpTransportServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
