/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import type {
  FileRoutesByPath,
  CreateServerFileRoute,
} from '@tanstack/react-start/server'
import {
  createServerRoute,
  createServerFileRoute,
} from '@tanstack/react-start/server'

import { ServerRoute as DotwellKnownOauthAuthorizationServerRouteImport } from './../../src/routes/[.]well-known.oauth-authorization-server'
import { ServerRoute as ApiAuthSplatRouteImport } from './../../src/routes/api/auth/$'
import { ServerRoute as ApiAiChatRouteImport } from './../../src/routes/api/ai/chat'
import { ServerRoute as ApiAiChatRagRouteImport } from './../../src/routes/api/ai/chat.rag'
import { ServerRoute as ApiAiChatImageGenerationRouteImport } from './../../src/routes/api/ai/chat.image.generation'

// Create/Update Routes

const rootRoute = createServerRoute()

const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRoute,
  } as any)

const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRoute,
} as any)

const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRoute,
} as any)

const ApiAiChatRagRoute = ApiAiChatRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => ApiAiChatRoute,
} as any)

const ApiAiChatImageGenerationRoute =
  ApiAiChatImageGenerationRouteImport.update({
    id: '/image/generation',
    path: '/image/generation',
    getParentRoute: () => ApiAiChatRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-start/server' {
  interface FileRoutesByPath {
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/ai/chat/rag': {
      id: '/api/ai/chat/rag'
      path: '/rag'
      fullPath: '/api/ai/chat/rag'
      preLoaderRoute: typeof ApiAiChatRagRouteImport
      parentRoute: typeof ApiAiChatRouteImport
    }
    '/api/ai/chat/image/generation': {
      id: '/api/ai/chat/image/generation'
      path: '/image/generation'
      fullPath: '/api/ai/chat/image/generation'
      preLoaderRoute: typeof ApiAiChatImageGenerationRouteImport
      parentRoute: typeof ApiAiChatRouteImport
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './../../src/routes/[.]well-known.oauth-authorization-server' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/.well-known/oauth-authorization-server']['parentRoute'],
    FileRoutesByPath['/.well-known/oauth-authorization-server']['id'],
    FileRoutesByPath['/.well-known/oauth-authorization-server']['path'],
    FileRoutesByPath['/.well-known/oauth-authorization-server']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/ai/chat' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/ai/chat']['parentRoute'],
    FileRoutesByPath['/api/ai/chat']['id'],
    FileRoutesByPath['/api/ai/chat']['path'],
    FileRoutesByPath['/api/ai/chat']['fullPath'],
    ApiAiChatRouteChildren
  >
}
declare module './../../src/routes/api/auth/$' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/auth/$']['parentRoute'],
    FileRoutesByPath['/api/auth/$']['id'],
    FileRoutesByPath['/api/auth/$']['path'],
    FileRoutesByPath['/api/auth/$']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/ai/chat.rag' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/ai/chat/rag']['parentRoute'],
    FileRoutesByPath['/api/ai/chat/rag']['id'],
    FileRoutesByPath['/api/ai/chat/rag']['path'],
    FileRoutesByPath['/api/ai/chat/rag']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/ai/chat.image.generation' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/ai/chat/image/generation']['parentRoute'],
    FileRoutesByPath['/api/ai/chat/image/generation']['id'],
    FileRoutesByPath['/api/ai/chat/image/generation']['path'],
    FileRoutesByPath['/api/ai/chat/image/generation']['fullPath'],
    unknown
  >
}

// Create and export the route tree

interface ApiAiChatRouteChildren {
  ApiAiChatRagRoute: typeof ApiAiChatRagRoute
  ApiAiChatImageGenerationRoute: typeof ApiAiChatImageGenerationRoute
}

const ApiAiChatRouteChildren: ApiAiChatRouteChildren = {
  ApiAiChatRagRoute: ApiAiChatRagRoute,
  ApiAiChatImageGenerationRoute: ApiAiChatImageGenerationRoute,
}

const ApiAiChatRouteWithChildren = ApiAiChatRoute._addFileChildren(
  ApiAiChatRouteChildren,
)

export interface FileRoutesByFullPath {
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}

export interface FileRoutesByTo {
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/ai/chat': typeof ApiAiChatRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ai/chat/rag': typeof ApiAiChatRagRoute
  '/api/ai/chat/image/generation': typeof ApiAiChatImageGenerationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/.well-known/oauth-authorization-server'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/ai/chat/rag'
    | '/api/ai/chat/image/generation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/.well-known/oauth-authorization-server'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/ai/chat/rag'
    | '/api/ai/chat/image/generation'
  id:
    | '__root__'
    | '/.well-known/oauth-authorization-server'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/ai/chat/rag'
    | '/api/ai/chat/image/generation'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  ApiAiChatRoute: typeof ApiAiChatRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  ApiAiChatRoute: ApiAiChatRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/.well-known/oauth-authorization-server",
        "/api/ai/chat",
        "/api/auth/$"
      ]
    },
    "/.well-known/oauth-authorization-server": {
      "filePath": "[.]well-known.oauth-authorization-server.ts"
    },
    "/api/ai/chat": {
      "filePath": "api/ai/chat.ts",
      "children": [
        "/api/ai/chat/rag",
        "/api/ai/chat/image/generation"
      ]
    },
    "/api/auth/$": {
      "filePath": "api/auth/$.ts"
    },
    "/api/ai/chat/rag": {
      "filePath": "api/ai/chat.rag.ts",
      "parent": "/api/ai/chat"
    },
    "/api/ai/chat/image/generation": {
      "filePath": "api/ai/chat.image.generation.ts",
      "parent": "/api/ai/chat"
    }
  }
}
ROUTE_MANIFEST_END */
