/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import type {
  FileRoutesByPath,
  CreateServerFileRoute,
} from '@tanstack/react-start/server'
import {
  createServerRoute,
  createServerFileRoute,
} from '@tanstack/react-start/server'

import { ServerRoute as DotwellKnownOauthAuthorizationServerRouteImport } from './../../src/routes/[.]well-known.oauth-authorization-server'
import { ServerRoute as ApiAuthSplatRouteImport } from './../../src/routes/api/auth/$'

// Create/Update Routes

const rootRoute = createServerRoute()

const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRoute,
  } as any)

const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-start/server' {
  interface FileRoutesByPath {
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module './../../src/routes/[.]well-known.oauth-authorization-server' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/.well-known/oauth-authorization-server']['parentRoute'],
    FileRoutesByPath['/.well-known/oauth-authorization-server']['id'],
    FileRoutesByPath['/.well-known/oauth-authorization-server']['path'],
    FileRoutesByPath['/.well-known/oauth-authorization-server']['fullPath'],
    unknown
  >
}
declare module './../../src/routes/api/auth/$' {
  const createServerFileRoute: CreateServerFileRoute<
    FileRoutesByPath['/api/auth/$']['parentRoute'],
    FileRoutesByPath['/api/auth/$']['id'],
    FileRoutesByPath['/api/auth/$']['path'],
    FileRoutesByPath['/api/auth/$']['fullPath'],
    unknown
  >
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRoutesByTo {
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/.well-known/oauth-authorization-server' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/.well-known/oauth-authorization-server' | '/api/auth/$'
  id: '__root__' | '/.well-known/oauth-authorization-server' | '/api/auth/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

const rootRouteChildren: RootRouteChildren = {
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/.well-known/oauth-authorization-server",
        "/api/auth/$"
      ]
    },
    "/.well-known/oauth-authorization-server": {
      "filePath": "[.]well-known.oauth-authorization-server.ts"
    },
    "/api/auth/$": {
      "filePath": "api/auth/$.ts"
    }
  }
}
ROUTE_MANIFEST_END */
